name: bonsoir_linux_dbus
description: Linux platform interface for bonsoir package. This package is useful for Linux desktop systems where Avahi is a commonly installed mDNS daemon.
version: '0.2.0'
homepage: https://github.com/Piero512/bonsoir_linux_dbus
repository: https://github.com/Piero512/bonsoir_linux_dbus

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  dbus: ^0.7.1
  meta: ^1.3.0
  bonsoir_platform_interface: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  async:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    implements: bonsoir
    platforms:
      linux:
        dartPluginClass: AvahiBonsoir
