name: bonsoir_linux_dbus
description: Linux platform interface for bonsoir package.
version: 0.0.1+2
homepage: https://github.com/Piero512/bonsoir_linux_dbus
repository: https://github.com/Piero512/bonsoir_linux_dbus

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  dbus: ^0.1.2
  bonsoir_platform_interface: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    implements: bonsoir
    platforms:
      linux:
        dartPluginClass: BonsoirLinuxDBus
